### PR TITLE
remove duplicate gps2utc

### PR DESCRIPTION
**Pull request by cheops**
gps2utc is present 2 times in the file

### CODE REVIEW

**Comment by davidallen353** [comment]
Thanks for point this out. The change needs to happen in the Jupyter notebooks because this project uses nbdev. I am making the corresponding change.

**Comment by davidallen353** [comment]
Fixed in #12

**Comment by davidallen353** [comment]
Fixed in #12

**Comment by cheops** [comment]
Thanks for the cleanup!

**Pull request closed without merging**
